from converter import *
from makebatches import *
from rbm import rbm
from backprop import *

MAX_EPOCH = 10
NUM_HID = 1000
NUMPEN = 500
NUMPEN2 = 250
NUMOPEN = 30

print('Converting Raw files into Matlab format')
# converter()

print('Pretraining a deep autoencoder.')
print('The Science paper used 50 epochs. This uses', MAX_EPOCH)

BATCH_DATA = makebatches()
NUM_CASES, NUM_DIMS, NUM_BATCHES = BATCH_DATA.shape
# print("BATCH_DATA.shape= ", BATCH_DATA.shape) #100, 784, 600

print('Pretraining Layer 1 with RBM: {}-{}'.format(NUM_DIMS, NUM_HID))
RESTART = 1
BATCHPOSHIDPROBS, HIDBIASES, VISHID, HIDBIASES, VISBIASES = rbm(BATCH_DATA, RESTART, NUM_HID, NUM_DIMS, MAX_EPOCH)
# print("BATCHPOSHIDPROBS.shape= ", BATCHPOSHIDPROBS.shape) #100, 1000
HIDRECBIASES = HIDBIASES

print('Pretraining Layer 2 with RBM: {}-{}'.format(NUM_HID, NUMPEN))
BATCH_DATA = BATCHPOSHIDPROBS
NUM_HID = NUMPEN
RESTART = 1
BATCHPOSHIDPROBS, HIDBIASES, VISHID, HIDBIASES, VISBIASES = rbm(BATCH_DATA, RESTART, NUM_HID, NUM_DIMS, MAX_EPOCH)
HIDPEN = VISHID
PENRECBIASES = HIDBIASES
HIDGENBIASES = VISBIASES

print('Pretraining Layer 3 with RBM: {}-{}'.format(NUMPEN, NUMPEN2))
BATCH_DATA = BATCHPOSHIDPROBS
NUM_HID = NUMPEN2
RESTART = 1
BATCHPOSHIDPROBS, HIDBIASES, VISHID, HIDBIASES, VISBIASES = rbm(BATCH_DATA, RESTART, NUM_HID, NUM_DIMS, MAX_EPOCH)
HIDPEN2 = VISHID
PENRECBIASES2 = HIDBIASES
HIDGENBIASES2 = VISBIASES

print('Pretraining Layer 4 with RBM: {}-{}'.format(NUMPEN2, NUMOPEN))
BATCH_DATA = BATCHPOSHIDPROBS
NUM_HID = NUMOPEN
RESTART = 1
BATCHPOSHIDPROBS, HIDBIASES, VISHID, HIDBIASES, VISBIASES = rbm(BATCH_DATA, RESTART, NUM_HID, NUM_DIMS, MAX_EPOCH)
HIDTOP = VISHID
TOPRECBIASES = HIDBIASES
TOPGENBIASES = VISBIASES

print('END of Pretraining Layer 4 with RBM: {}-{}'.format(NUMPEN2, NUMOPEN))

backprop(BATCHDATA, VISHID, HIDRECBIASES, HIDPEN, PENRECBIASES)

